icon_theme = "Paper"

[[start]]
type = "menu"
label = "󱓞"

[[start]]
type = "workspaces"

[[start]]
type = "launcher"
favorites = ["firefox"]

[start.truncate]
mode = "end"
max_length = 30

[[center]]
type = "music"
player_type = "mpd"

[[end]]
type = "battery"
show_if = "[ -f /sys/class/power_supply/BAT0 ]"

[[end]]
type = "sys_info"
format = [
    "{cpu_percent}% ",
    "{memory_percent}% ",
]

[end.interval]
cpu = 1

[[end]]
type = "clipboard"
max_items = 5

[end.truncate]
mode = "end"
length = 30

[[end]]
type = "volume"

[[end]]
type = "custom"
name = "power-menu"
class = "power-menu"

[[end.bar]]
type = "button"
name = "power-btn"
label = ""
on_click = "popup:toggle"

[[end.popup]]
type = "box"
orientation = "vertical"

[[end.popup.widgets]]
type = "label"
name = "header"
label = "Power menu"

[[end.popup.widgets]]
type = "box"
name = "buttons"

[[end.popup.widgets.widgets]]
type = "button"
class = "power-btn"
label = "<span>󰐥</span>"
on_click = "!shutdown now"

[[end.popup.widgets.widgets]]
type = "button"
class = "power-btn"
label = "<span>󰜉</span>"
on_click = "!reboot"

[[end]]
type = "tray"

[[end]]
type = "clock"

[[end]]
type = "notifications"

