start:
  - type: menu
    center:
      - type: xdg_entry
        label: Accessories
        icon: accessories
        categories:
          - Accessibility
          - Core
          - Legacy
          - Utility
      - type: xdg_entry
        label: Development
        icon: applications-development
        categories:
          - Development
      - type: xdg_entry
        label: Education
        icon: applications-education
        categories:
          - Education
      - type: xdg_entry
        label: Games
        icon: applications-games
        categories:
          - Games
      - type: xdg_entry
        label: Graphics
        icon: applications-graphics
        categories:
          - Graphics
      - type: xdg_entry
        label: Multimedia
        icon: applications-multimedia
        categories:
          - Audio
          - Video
          - AudioVideo
      - type: xdg_entry
        label: Network
        icon: applications-internet
        categories:
          - Network
      - type: xdg_entry
        label: Office
        icon: applications-office
        categories:
          - Office
      - type: xdg_entry
        label: Science
        icon: applications-science
        categories:
          - Science
      - type: xdg_entry
        label: System
        icon: applications-system
        categories:
          - Emulator
          - System
      - type: xdg_other
      - type: xdg_entry
        label: Settings
        icon: preferences-system
        categories:
          - Settings
          - Screensaver


